spring:
  profiles:
    active: local #local,dev,real
    
  mvc:
    view: #view 경로 및 확장자 지정
      prefix: /WEB-INF/views/
      suffix: .jsp
  
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: 1230
    driver-class-name: org.h2.Driver  
      
  devtools: #View reload
    livereload:
      enabled: true
    restart: #컨트롤러, 모델단이 바뀌었을 때 프로젝트 재시작 설정(정확히는 classpath에 있는 모든 파일)
      enabled: true
  
  servlet:
    multipart:
      max-file-size: 50MB #파일 한 개당 최대 사이즈
      max-request-size: 200MB #요청당 최대 파일 크기
          
mybatis: #mybatis 설정
  type-aliases-package: kr.spring.**.vo
  mapper-locations: kr/spring/**/dao/*.xml
  
logging: #로그 지정
  level:
    '[kr.spring]': debug
    
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true #http 인코딩 지원을 활성화할지 여부
      force: true