DROP TABLE IF EXISTS MAILPLUG_REPLY;
DROP TABLE IF EXISTS MAILPLUG_BOARD;

CREATE TABLE MAILPLUG_BOARD (
    BOARD_NUM INT AUTO_INCREMENT PRIMARY KEY ,
    USER_IP VARCHAR(50) NOT NULL,
    USER_NICKNAME VARCHAR(50) NOT NULL,
    BOARD_PASSWD VARCHAR(50) NOT NULL,
    BOARD_TITLE VARCHAR(300) NOT NULL,
    BOARD_INFO VARCHAR(1000) NOT NULL,
    BOARD_HIT INT DEFAULT 0 NOT NULL,
    BOARD_REG_DATE DATE DEFAULT CURRENT_TIMESTAMP NOT NULL
);


CREATE TABLE MAILPLUG_REPLY (
	REPLY_NUM INT AUTO_INCREMENT PRIMARY KEY,
	USER_IP VARCHAR(50) NOT NULL,
	BOARD_NUM INT,
	REPLY_NICKNAME VARCHAR(50) NOT NULL,
	REPLY_INFO VARCHAR(1000) NOT NULL,
	REPLY_REG_DATE DATE DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (BOARD_NUM) REFERENCES MAILPLUG_BOARD(BOARD_NUM)
);